spring:
    profiles: dev   #当前配置的ID、名字，区分配置的标识
    application:
        name: config-dev-8888
        
---

spring:
    profiles: test   #当前配置的ID、名字，区分配置的标识
    application:
        name: config-test-8888